### ISSUE TITLE
Promising library, ideas for improvement

### ISSUE THREAD

**Issue by gijs** [lizardsystem/lizard-connector#16]
Hi!

This library has a lot of potential in my opinion! 

The readme is already quite good since it contains examples. 👍 

Here are some suggestions to improve lizard-connector:

- Make the coding interface more Pythonic. Ideally, it should hide REST details and look more like the Django ORM (see for example below)
- Use API keys instead of using the credentials that also allow access to my mail and laptop. I know this requires lots of API work, but it's something to keep in mind
- Read the config (ie. API key) from a `.lizardrc` file
- Publish this to the PyPI so it's pip installable
- Improve the documentation and examples to cover the basic use cases

An example of a workflow I'd prefer goes like this:
```bash
$ pip install lizard-connector
$ python
````
```python
>>> from lizard_connector import Client
>>> client = Client('https://demo.lizard.net/api/v3', 'MY_API_KEY')
>>> timeserie = client.timeseries.get('5219e208-ae2b-4c48-939c-3c9371eb8577')
>>> timeserie.objects.filter(date__range=["2016-01-01", "2017-01-01"])
```

Thinking even further, we could expand this library into a full-blown CLI for Lizard. A CLI that not only fetches data, but also allows things like ingesting of massive raster datasets to our raster service. In concept similar to tools like the [bq command line tool for BigQuery](https://cloud.google.com/bigquery/bq-command-line-tool).

Thanks!

**Comment by RoelvandenBerg** [comment]
@jackieleng wijs ook hierop: http://python.apichecklist.com/

**Comment by gijs** [comment]
get/create

**Comment by jackieleng** [comment]
Voorbeeld van __getattr__ override: https://sendgrid.com/blog/using-python-to-implement-a-fluent-interface-to-any-rest-api/

**Comment by RoelvandenBerg** [comment]
oi. Had ik Jackies comment maar gelezen...
Ik heb weer een stap gemaakt. Een hoop van de bovenstaande punten heb ik nog niet verwerkt (http://python.apichecklist.com/), maar ik stel voor dat we (in iedergeval met @jackieleng ) doorspreken wat we nu hebben en dat ik met @remcogerlich doorspreek of ik er een versie 0.? van maak op pypi. (wat is de mvp?)

Binnenkort komt er een commit.

**Comment by RoelvandenBerg** [comment]
`lizard-connector` is now on [pypi](https://pypi.org/project/lizard-connector/)
This latest release contains the fixes for this issue: 
- Make the coding interface more Pythonic. Ideally, it should hide REST details and look more like the Django ORM (see for example below)
- Publish this to the PyPI so it's pip installable
- Improve the documentation and examples to cover the basic use cases

The api keys fall beyond the scope of this library. When lizard-nxt incorporates this, this can get a place within this library:
- Use API keys instead of using the credentials that also allow access to my mail and laptop. I know this requires lots of API work, but it's something to keep in mind
- Read the config (ie. API key) from a .lizardrc file

**Comment by gijs** [comment]
👍
